CREATE TABLE users (
    user_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname    VARCHAR2(100),
    user_name   VARCHAR2(50) UNIQUE NOT NULL,
    user_salt   VARCHAR2(50),
    password    VARCHAR2(200),
    is_active   NUMBER(1) DEFAULT 1
);
